config/routes.rb
Rails.application.routes.draw do

  resources :users, :only => [:new, :create, :show]
  resource :session, :only => [:new, :create, :destroy]
  resources :subs
  resources :posts, :only => [:new, :create, :show, :edit, :update, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, presence: true
  belongs_to :sub
  belongs_to :author,
    class_name: :User,
    primary_key: :id,
    foreign_key: :author_id

end

app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :title, :moderator_id, presence: true
  validates :moderator_id, uniqueness: {scope: :title}

  belongs_to :moderator,
    class_name: :User,
    primary_key: :id,
    foreign_key: :moderator_id

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum:6, allow_nil: true}

  has_many :subs
  
  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user
      if user.is_password?(password)
        return user
      else
        return nil
      end
      nil
    end
    nil
  end

  def generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    pass = BCrypt::Password.new(self.password_digest)
    pass.is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user = User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :validate_author, only: [:edit, :update]

  def new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    # @post.sub_id = params[:post][:sub_id][0]
    if @post.save
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    parent_sub = @post.sub
    @post.destroy
    redirect_to sub_url(parent_sub)
  end

  private
  def post_params
    # debugger
    params.require(:post).permit(:title, :url, :content, sub_id: [])
  end

  def validate_author
    @post = Post.find(params[:id])
    if current_user.nil?
      redirect_to new_session_url
    elsif current_user.id != @post.author_id
      redirect_to post_url(@post)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    #session[:session_token]
    #username, password - find_by_credentials
    @user = User.find_by_credentials(params[:user][:username],
    params[:user][:password])
    if @user.valid?
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    if current_user
      current_user.reset_session_token
      session[:session_token] = nil
    end
    redirect_to new_session_url
  end

  private
  # def user_params
  #   params.require(:user).permit(:username, :password)
  # end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :validate_moderator, only: [:edit]

  def new
    render :new
  end

  def index
    @subs = Sub.all
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def validate_moderator
    @sub = Sub.find(params[:id])
    if current_user.id != @sub.moderator_id
      redirect_to sub_url(@sub)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
    <h2>Welcome, "<%= current_user.username %>"</h2>
    <%= button_to "Logout", session_url, method: 'delete' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<form action="<%= post_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type='hidden' name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title:
    <input type="text" name="post[title]" value= "<%= @post.title %>">
  </label>
  <br>
  <label>Content:
    <input type="text" name="post[content]" value= "<%= @post.content %>">
  </label>

  <button>Submit</button>
</form>

app/views/posts/new.html.erb
<h1>New Post</h1>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<% if flash[:errors] %>
  <p><%= flash[:errors].join(", ") %></p>
<% end %>

<form action="<%= posts_url %>" method="post">
  <input type='hidden' name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title:
    <input type="text" name="post[title]">
  </label>
  <br>
  <label>Content:
    <input type="text" name="post[content]">
  </label>

  <ul>
    <% @subs.each do |subb| %>
      <li><input type="checkbox" name="post[sub_id][]" value="<%=subb.id%>"> <%=subb.title%></li>
    <% end %>
    </ul>
  <br>

  <button>Submit</button>
</form>

app/views/posts/show.html.erb
<h1>Post: <%= @post.title %> </h1>
<h2>Content: <%= @post.content%></h2>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <br>
  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <br>
  <button>Submit</button>
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>
<br>
<ul>
  <% @subs.each do |subb| %>
    <li> <%= subb.title %> </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create Sub</h1>
<form action="<%=subs_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Title:
    <input type="text" name="sub[title]">
  </label>
  <br>

  <label>Description:
    <input type="text" name="sub[description]">
  </label>
  <br>

  <button>Submit</button>

</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

app/views/users/new.html.erb
<h1>Create New User<h1>
<form action= "<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="username">Username:</label>
  <input id="username" type="text" name="user[username]">
  <br>

  <label for="password">Password:</label>
  <input id="password" type="password" name="user[password]">
  <br>

  <button>Sign In</button>
</form>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %> </h1>
<h3>This is the show page</h3>